name: Build AssetStudioGUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build AssetStudioGUI
        run: dotnet build AssetStudioGUI/AssetStudioGUI.csproj -c Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AssetStudioGUI-Build
          path: AssetStudioGUI/bin/Release/net8.0-windows/
